# Generated by Django 4.0.2 on 2022-02-08 11:29

import courseapi.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('details', models.TextField()),
                ('image', models.ImageField(upload_to=courseapi.models.upload_category_image)),
                ('created', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Category Name',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('details', models.TextField()),
                ('price', models.FloatField(default=100.0)),
                ('image', models.ImageField(upload_to=courseapi.models.upload_course_image)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='courseapi.category')),
            ],
            options={
                'verbose_name_plural': 'Course Name',
            },
        ),
    ]
